### ISSUE TITLE
Changing resolution of generator output

### ISSUE THREAD

**Issue by squishytofu042** [Latope2-150/Progressive_Growing_of_GANs-PyTorch#1]
Hello, the default resolution is 1024x1024 (128x128 per MNIST character). I want to change it to 2048x2048 (256x256 per MNIST character). Is changing maxRes=8 to maxRes=9 all I have to do? I have tried this and my sim has been running for over a day, but it is still outputting 1024x1024. Please help!

**Comment by jeromerony** [comment]
Hi,
I'm not sure what you mean by 128x128 per MNIST character since MNIST is 28x28 gray level images.

Changing maxRes to 9 will indeed change the maximum resolution of the networks to 2048x2048. For training, you also need to change the args passed to the Progress class with respect to the network creation.

**Comment by squishytofu042** [comment]
Hello! 

So, to clarify, the training data for MNIST is 28x28. The default output of the generator is 1024x1024. Since the batch size is 64, each character produced by the generator is 1024/8 = 128 pixel size. 

Do you mean this: P = Progress(opt.n_iter, 3, opt.batchSizes)? What would need to be changed?

**Comment by jeromerony** [comment]
I'm not sure I'm following your reasoning: in the training for MNIST, the original images are 28x28, padded to obtain 32x32 images. The created network with parameter MAX_RES=3 outputs images at 32x32 resolution.
The default output of the generator is simply what we chose it to be, but it can never be more than the original images resolution.

**Comment by squishytofu042** [comment]
Yes, I've noticed that the images are padded. But that's what you've done to the original 28x28 images. When the generator produces fake images, it progressively grows in size. The output has 64 images in an 8x8 grid. This grid is a square of size 1024x1024 pixels, and each generated character has a size 128x128 pixels. Does this make sense?

**Comment by jeromerony** [comment]
I think you are mistaking the output of the generator with the saved sampled images. The output of the generator for MNIST will never be of greater resolution than 32x32.

**Comment by squishytofu042** [comment]
Oh I see. I want to generate characters that are 1024x1024 in pixel size (i.e. 1 character has a resolution 1024x1024). Is this possible? I thought the purpose of PGANs was to 'produce images of unprecedented quality'. For example, celebA images were able to be produced at 1024x1024 resolution.

**Comment by jeromerony** [comment]
The goal of the PG-GAN is to stabilize the training of a GAN at high resolution. However, you can not generate higher-resolution images than what you have in your database. So, to generate 1024x1024 images of faces, you need a database of faces which are already 1024x1024.

**Comment by squishytofu042** [comment]
Surely if I use an image processing technique to increase the resolution of MNIST to 1024x1024 whilst maintaining quality, I can do this then?

**Comment by jeromerony** [comment]
If it was possible, then yes.

**Comment by squishytofu042** [comment]
Ah that's great. I've been able to do that, but I'm unsure what arguments passed to the progress class need to be changed?

**Comment by jeromerony** [comment]
I updated the code to be clearer on that point, you just need to change the MAX_RES variable.

**Comment by squishytofu042** [comment]
Thank you! But I get an error saying 'batchSizeList must be a list of int > 0 and of length pmax+1'
AssertionError: batchSizeList must be a list of int > 0 and of length pmax+1 

when I change 'MAX_RES to 5'. I'm trying Omniglot and the images are 105x105 in size. I padded it to 128x128 by 'transforms.Pad((11.5, 11.5))'. Then 4*2^5=128. 

How can I fix this?

**Comment by jeromerony** [comment]
I think the message is self explanatory, your batchSizeList must be of
length pmax + 1 which is equal to MAX_RES + 1, so if you MAX_RES=5,
batchSizeList must be of length 5+1

Le jeu. 7 juin 2018 à 19:28, squishytofu042 <notifications@github.com> a
écrit :
