### ISSUE TITLE
How to incorporate tanh activation ?

### ISSUE THREAD

**Issue by xchhuang** [Latope2-150/Progressive_Growing_of_GANs-PyTorch#4]
Hi, first thanks for this great project.

But I met problems when I tried to add tanh at the output as the model can easily collapse. Have you experienced with that as well ? Thanks in advance.

**Comment by emmanueliarussi** [comment]
same problem here!

**Comment by jeromerony** [comment]
Hi,

I am not sure I understand your problem. I have not tried using tanh activation at the output of the generator.

**Comment by xchhuang** [comment]
@jeromerony 

Okay thanks. Yes, I mean using tanh activation at the output of generator when we need to reconstruction data with clear background and foreground.
