### ISSUE TITLE
Torch summary outputs multiple activation layers

### ISSUE THREAD

**Issue by saxenamudit** [Latope2-150/Progressive_Growing_of_GANs-PyTorch#5]
I tried using torch summary for the generator and discriminator:

**MAX_RES = 8
G = Generator(max_res=MAX_RES, nch=16, nc=3, bn=opt.BN, ws=opt.WS, pn=opt.PN).to(DEVICE)
D = Discriminator(max_res=MAX_RES, nch=16, nc=3, bn=opt.BN, ws=opt.WS).to(DEVICE)
summary(G,(512,1,1))
summary(D,(3,1024,1024))**

Surprisingly i got multiple LeakyReLU in the output. As such:
https://colab.research.google.com/drive/1qjkV6N9AI7G-oUcCqPqAXHpHooWMeb7c?usp=sharing

Is there any possible reason for this?

**Comment by jeromerony** [comment]
Hi,
I don't know. It has to do with how torchsummary hooks into the model.

A quick fix is to not re-use the same instance of LeakyReLU everywhere, i.e. create a new LeakyReLU object every time.

Cheers
