### ISSUE TITLE
Unable to resume train after loading saved model

### ISSUE THREAD

**Issue by stefanorosss** [Latope2-150/Progressive_Growing_of_GANs-PyTorch#6]
I have been trying to add an option to resume training from a saved model, like this

```
    if opt.resumetraining:
        _path = 'Results/Models/'
        regex = re.compile(r'\d+')
        _epoch = max([[int(x) for x in regex.findall(_filename)][1] for _filename in os.listdir(_path)])
        G =  torch.load(_path + f'G_nch-{opt.nch}_epoch-{_epoch}.pth')
        D =  torch.load(_path + f'D_nch-{opt.nch}_epoch-{_epoch}.pth')
        Gs =  torch.load(_path + f'Gs_nch-{opt.nch}_epoch-{_epoch}.pth')
        epoch = _epoch + 1
```

Unfortunately, while the loaded models work fine, I don't seem able to train them using the script.
I noticed that all the saved images where the same and tought it was an issue with Gs (tried to initialize it as a deepcopy of G, but no luck), before realizing that the weights were staying the same across epochs...

I have modified the script a bit to adapt it to my dataset but nothing related to training, everything is fine if I don't pass the --resumetraining parameter.

Any idea about why this could be?

Thanks a lot for the great work!

**Comment by jeromerony** [comment]
Hi! Thanks for the interest in this work.

Your problem description is a bit short in order for me to help you. Where did you put the code sample that you provided?

**Comment by stefanorosss** [comment]
Just before the declaration of the two optimizers.
 Anyway, everything seems to work fine if I remove the  `cudnn.benchmark = True` from the training loop, so I'm closing this.
